services:
  # 1. Datenbank (MariaDB)
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghostshare_db  # Diese DB wird beim ersten Start erstellt
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. File Storage (MinIO)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web-Console
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: